<%
public_ip = "10.10.0.81"
%>
---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 8192
  network:
  - ["forwarded_port", {guest: 443, host: 9443}]
  - ["private_network", {ip: <%= public_ip %>}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing
  # environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: 15
  # Copy secret to /tmp/kitchen on test VM. Kitchen tries to gather secrets
  # before any recipes had a chance to run -> we cannot use a recipe to put the
  # secrets file in place.
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret
  roles_path: roles
  environments_path: environments
  attributes:
    openstack:
      secret:
        key_path: /tmp/kitchen/encrypted_data_bag_secret
  client_rb:
    environment: integration
    treat_deprecation_warnings_as_errors: true
    resource_cloning: false
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04
  - name: centos-7
    driver:
      box: bento/centos-7

suites:
  - name: default
    run_list:
      - recipe[openstack_test]
      - role[allinone]
      - role[minimal_test]
    provisioner:
      client_rb:
        environment: allinone
  - name: minimal
    run_list:
      - recipe[openstack_test]
      - role[minimal]
      - role[minimal_test]
  - name: common
    run_list:
      - recipe[openstack_test]
      - role[common]
  - name: openstackclient
    run_list:
      - recipe[openstack_test]
      - role[openstackclient]
  - name: ops-database
    run_list:
      - recipe[openstack_test]
      - role[ops_database]
  - name: ops-messaging
    run_list:
      - recipe[openstack_test]
      - role[ops_messaging]
  - name: identity
    run_list:
      - recipe[openstack_test]
      - role[identity]
      - role[identity_test]
  - name: image
    run_list:
      - recipe[openstack_test]
      - role[image]
      - role[image_test]
  - name: network
    run_list:
      - recipe[openstack_test]
      - role[network]
      - role[network_test]
  - name: compute
    run_list:
      - recipe[openstack_test]
      - role[compute]
      - role[compute_test]
  - name: orchestration
    run_list:
      - recipe[openstack_test]
      - role[orchestration]
      - role[orchestration_test]
  - name: block-storage
    run_list:
      - recipe[openstack_test]
      - role[block_storage]
      - role[block_storage_test]
  - name: bare-metal
    run_list:
      - recipe[openstack_test]
      - role[bare_metal]
      - role[bare_metal_test]
  - name: telemetry
    run_list:
      - recipe[openstack_test]
      - role[telemetry]
      - role[telemetry_test]
  - name: dns
    run_list:
      - recipe[openstack_test]
      - role[dns]
      - role[dns_test]
  - name: dashboard
    run_list:
      - recipe[openstack_test]
      - role[dashboard]
      - role[dashboard_test]
