- job:
    name: openstack-chef-delivery
    parent: base
    description: Run Chef Delivery tests with openstack-chef
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-delivery.yaml
    run: playbooks/delivery.yaml
    timeout: 1800
    voting: false # TODO(ramereth): Remove after this gets merged

- job:
    name: openstack-chef-integration-ubuntu
    parent: base
    nodeset: ubuntu-bionic
    description: Run integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 5400
    voting: false # TODO(ramereth): Remove after this gets merged

- job:
    name: openstack-chef-minimal-integration-ubuntu
    parent: base
    nodeset: ubuntu-bionic
    description: Run minimal integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/minimal.yaml
    post-run: playbooks/post.yaml
    timeout: 5400
    voting: false # TODO(ramereth): Remove after this gets merged

- job:
    name: openstack-chef16-minimal-integration-ubuntu
    parent: openstack-chef-minimal-integration-ubuntu
    vars:
      openstack_chef_client_version: 16

- job:
    name: openstack-chef-integration-centos
    parent: base
    nodeset: centos-7
    description: Run integration tests with openstack-chef on CentOS 7
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 5400
    voting: false # TODO(ramereth): Remove after this gets merged

- job:
    name: openstack-chef-minimal-integration-centos
    parent: base
    nodeset: centos-7
    description: Run minimal integration tests with openstack-chef on CentOS 7
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/minimal.yaml
    post-run: playbooks/post.yaml
    timeout: 5400
    voting: false # TODO(ramereth): Remove after this gets merged

- job:
    name: openstack-chef16-minimal-integration-centos
    parent: openstack-chef-minimal-integration-centos
    vars:
      openstack_chef_client_version: 16

- job:
    name: openstack-cinc16-integration-ubuntu
    parent: openstack-chef-integration-ubuntu
    vars:
      openstack_chef_client_type: cinc
      openstack_chef_client_version: 16

- job:
    name: openstack-cinc-integration-ubuntu
    parent: openstack-chef-integration-ubuntu
    vars:
      openstack_chef_client_type: cinc

- job:
    name: openstack-cinc16-integration-centos
    parent: openstack-chef-integration-centos
    vars:
      openstack_chef_client_type: cinc
      openstack_chef_client_version: 16

- job:
    name: openstack-cinc-integration-centos
    parent: openstack-chef-integration-centos
    vars:
      openstack_chef_client_type: cinc

- project-template:
    name: openstack-chef-repo-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-centos
        - openstack-chef-integration-ubuntu
        - openstack-cinc16-integration-centos
        - openstack-cinc16-integration-ubuntu
        - openstack-cinc-integration-centos
        - openstack-cinc-integration-ubuntu
    gate:
      queue: openstack-chef
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-centos
        - openstack-chef-integration-ubuntu
        - openstack-cinc16-integration-centos
        - openstack-cinc16-integration-ubuntu
        - openstack-cinc-integration-centos
        - openstack-cinc-integration-ubuntu

- project-template:
    name: openstack-chef-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-centos
        - openstack-chef-integration-ubuntu
        - openstack-chef-minimal-integration-centos
        - openstack-chef-minimal-integration-ubuntu
        - openstack-chef16-minimal-integration-centos
        - openstack-chef16-minimal-integration-ubuntu
        - openstack-cinc16-integration-centos
        - openstack-cinc16-integration-ubuntu
        - openstack-cinc-integration-centos
        - openstack-cinc-integration-ubuntu
    gate:
      queue: openstack-chef
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-centos
        - openstack-chef-integration-ubuntu
        - openstack-chef-minimal-integration-centos
        - openstack-chef-minimal-integration-ubuntu
        - openstack-chef16-minimal-integration-centos
        - openstack-chef16-minimal-integration-ubuntu
        - openstack-cinc16-integration-centos
        - openstack-cinc16-integration-ubuntu
        - openstack-cinc-integration-centos
        - openstack-cinc-integration-ubuntu

- project:
    templates:
      - deploy-guide-jobs
      - publish-openstack-docs-pti
      - openstack-chef-repo-jobs
