- name: Install client
  script:
    cmd: "{{ openstack_chef_client_type }}-install.sh -v {{ openstack_chef_client_version }}"
  become: yes
- name: Create symlink for cinc
  file:
    state: link
    src: /opt/cinc
    dest: /opt/chef
  become: yes
  when: openstack_chef_client_type == 'cinc'
- name: Install berkshelf
  shell: /opt/chef/embedded/bin/gem install -N berkshelf
  become: yes
- name: Install cookstyle
  shell: /opt/chef/embedded/bin/gem install -N cookstyle
  become: yes
