- name: Install client
  script:
    cmd: "{{ openstack_chef_client_type }}-install.sh -v {{ openstack_chef_client_version }}"
  become: yes
- name: Create symlink for cinc
  file:
    state: link
    src: /opt/cinc
    dest: /opt/chef
  become: yes
  when: openstack_chef_client_type == 'cinc'
- name: Install berkshelf
  # TODO(ramereth): > 7.1.0 doesn't work with ruby 2.6 which is used on Chef/Cinc 15
  # Remove this once we remove testing for Chef/Cinc 15
  shell: /opt/chef/embedded/bin/gem install -N berkshelf -v 7.1.0
  become: yes
- name: Install cookstyle
  shell: /opt/chef/embedded/bin/gem install -N cookstyle
  become: yes
- name: Setup SELinux
  shell: "setenforce {{ openstack_selinux_setenforce }}"
  become: yes
  when: ansible_distribution == "CentOS"
